import { createSlice } from "@reduxjs/toolkit";

export const userSlice = createSlice({
  name: "userSlice",
  initialState: {
    user: {
      id: "",
      email: "",
      phone: "",
      created_at: "",
      updated_at: "",
      name: "",
      shop_id: "",
      cotter_client_id: "",
      authy_id: "",
      country_code: "",
      phone_with_code: "",
      device_token: "",
      is_hardcoded: "",
      otp: "",
      otp_expired: "",
      is_block: "",
      authy_id_sms: "",
      app_version: "",
      beta_user: "",
      shop: {
        id: "",
        name: "",
        address: "",
        phone: "",
        image_file_name: "",
        image_content_type: "",
        image_file_size: "",
        image_updated_at: "",
        created_at: "",
        updated_at: "",
        source_latitude: "",
        source_longitude: "",
        postal_code: "",
        detail_address: "",
        inv_address: "",
        inv_phone: "",
        referrer: "",
        is_hardcoded: "",
        refferal_code: "",
        shop_url: "",
        status: "",
        holiday_start: "",
        holiday_end: "",
        open_time: "",
        close_time: "",
        open_date: "",
        community_id: "",
        province_id: "",
        city_id: "",
        district_id: "",
        subdistrict_id: "",
        province_name: "",
        city_name: "",
        district_name: "",
        subdistrict_name: "",
        category: "",
        subcategory: "",
        instalation_source: "",
        tag: "",
        tags: "",
        mode: "",
        kp_registered: "",
        ks_registered: "",
        pin_is_set: "",
        is_payment_link: "",
        channel: "",
        bank_accounts: "",
        expeditions: "",
        auto_texts: "",
        products: "",
        features: "",
        settings: "",
        vouchers: "",
        province: {
          id: "",
          name: "",
        },
        city: {
          id: "",
          name: "",
        },
        district: {
          id: "",
          name: "",
        },
        subdistrict: {
          id: "",
          name: "",
          postcode: "",
        },
      },
    },
  },
  reducers: {
    setUser: (state, action) => {
      state.user = action.payload;
    },
  },
});
export const { setUser } = userSlice.actions;
export const selectUserSlice = (state) => state.userSlice.value;
